apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - name: capstone
          image: jees/capstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80
